name: Release Luma

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on version tags like v0.0.3

jobs:
  release:
    name: Build and Publish Release
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Create GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }} # Your Personal Access Token

      # Package Electron app
      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: npm run build

      # Upload release assets to GitHub
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/Luma-Setup-${{ github.ref_name }}.exe
          asset_name: Luma-Setup-${{ github.ref_name }}.exe
          asset_content_type: application/octet-stream
