name: Release Luma

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on version tags like v0.0.3

jobs:
  release:
    name: Build and Publish Release
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Package Electron app
      - name: Build Electron app
        run: npm run build

      # Publish to GitHub Releases
      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: npm run build
